### ISSUE TITLE
The error occurs occasionally when loading multiple houses simultaneously

### ISSUE THREAD

**Issue by WangJuan6** [allenai/procthor-10k#12]
Hi, I'm trying to load the multiple procthor-10k houses simultaneously， sometimes, the code works, but sometimes I get the following error :

```
Process ForkServerProcess-1:
Traceback (most recent call last):
  File "/home/omnisky/anaconda3/envs/proc_sem_expratio/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/omnisky/anaconda3/envs/proc_sem_expratio/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/media/omnisky/_dev_nvme1n1/wj/projects/envs/utils/vector_env.py", line 182, in _worker_env
    env = env_fn(*env_fn_args)
  File "/media/omnisky/_dev_nvme1n1/wj/projects/envs/__init__.py", line 134, in make_env_fn_alfred
    env = Sem_Exp_Env_Agent_Thor(args, scene_names, rank)
  File "/media/omnisky/_dev_nvme1n1/wj/projects/agents/sem_exp_thor.py", line 42, in __init__
    super().__init__(args, rank)
  File "/media/omnisky/_dev_nvme1n1/wj/projects/env/thor_env_code.py", line 123, in __init__
    self.dataset = prior.load_dataset("procthor-10k")
  File "/home/omnisky/anaconda3/envs/proc_sem_expratio/lib/python3.8/site-packages/prior/__init__.py", line 269, in load_dataset
    sha, token = _clone_repo(
  File "/home/omnisky/anaconda3/envs/proc_sem_expratio/lib/python3.8/site-packages/prior/__init__.py", line 211, in _clone_repo
    token = next(token for token in tokens.split("\n") if token.endswith("github.com"))
StopIteration
```

Can you help me to solve this problem?
Thanks,
Juan

**Comment by Galaxyphan** [comment]
hi, Have you solved this problem? Could you please tell me how to solve it?
