### ISSUE TITLE
Colab start_xserver() error

### ISSUE THREAD

**Issue by pioneer-innovation** [allenai/procthor-10k#4]
Hi @mattdeitke ,

When I run your colab demo, it returns error under the code:

```python
import ai2thor_colab
ai2thor_colab.start_xserver()
```

Error message:

    ERROR:tornado.general:Uncaught exception in ZMQStream callback
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 556, in _run_callback
        callback(*args, **kwargs)
      File "/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
        return fn(*args, **kwargs)
      File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
        return self.dispatch_shell(stream, msg)
      File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 239, in dispatch_shell
        sys.stdout.flush()
    ValueError: I/O operation on closed file.
    ERROR:tornado.general:Uncaught exception in zmqstream callback
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 577, in _handle_events
        self._handle_recv()
      File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 606, in _handle_recv
        self._run_callback(callback, msg)
      File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 556, in _run_callback
        callback(*args, **kwargs)
      File "/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
        return fn(*args, **kwargs)
      File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
        return self.dispatch_shell(stream, msg)
      File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 239, in dispatch_shell
        sys.stdout.flush()
    ValueError: I/O operation on closed file.
    ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7ff8a2c648c0>)
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/dist-packages/tornado/ioloop.py", line 758, in _run_callback
        ret = callback()
      File "/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
        return fn(*args, **kwargs)
      File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 661, in <lambda>
        self.io_loop.add_callback(lambda: self._handle_events(self.socket, 0))
      File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 577, in _handle_events
        self._handle_recv()
      File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 606, in _handle_recv
        self._run_callback(callback, msg)
      File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 556, in _run_callback
        callback(*args, **kwargs)
      File "/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
        return fn(*args, **kwargs)
      File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
        return self.dispatch_shell(stream, msg)
      File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 239, in dispatch_shell
        sys.stdout.flush()
    ValueError: I/O operation on closed file.

**Comment by mattdeitke** [comment]
Whoops, should now work! I have updated [ai2thor-colab](https://github.com/allenai/ai2thor-colab).

Thanks for the heads up :)
