### ISSUE TITLE
RuntimeError: KeyNotFoundException while rearranging houses from ProcThor

### ISSUE THREAD

**Issue by mariiak2021** [allenai/procthor-10k#6]
Hi @mattdeitke,

I'm trying to use ProcThor-10k dataset to generate some new scenes with rearrangement for the rearrangement-challenge.
While generating, I'm getting this error for some of the houses from ProcThor. So it's just for some of them - not all. I'm confused about which key is missing in the dictionary and how can I fix it.
I'm using only 1-room houses from ProcThor, if it helps. I did some experiments using 4.3.0 version of Ai2Thor and custom 0+391b3fae4d4cc026f1522e5acf60953560235971 as in colab for ProcThor, but seems the error is always same for the same scenes.
Will appreciate any help!

`[08/07 07:00:48 ERROR:] RearrangeProcTHORDatagenWorker 0: Exception when processing rearrange 4 {'scene': 'train_14', 'stage': 'train', 'seed': 24197580, 'reuse_i': 0, 'obj_name_to_avoid_positions': None, 'limits': {'room_openables': {'room|4': ['Fridge_5_0']}, 'max_pickupable': 20, 'max_receps': {'room|4': 10}}, 'scene_reuse_count': 2}        [multiprocessing_utils.py: 62]
Traceback (most recent call last):
  File "/dstore/home/mkhan/ai2thor-rearrangement-procthor/utils/multiprocessing_utils.py", line 56, in __init__
    res = self.work(job[0], job[2])
  File "datagen/procthor_datagen/datagen_runner.py", line 1185, in work
    data = generate_rearrangement_for_scene(
  File "datagen/procthor_datagen/datagen_runner.py", line 788, in generate_rearrangement_for_scene
    if not env.procthor_reset(scene_name=scene, force_reset=True):
  File "/dstore/home/mkhan/ai2thor-rearrangement-procthor/rearrange/procthor_rearrange/environment.py", line 577, in procthor_reset
    self.controller.step(
  File "/home/mkhan/anaconda3/envs/thor-rearrange/lib/python3.8/site-packages/ai2thor/controller.py", line 985, in step
    raise RuntimeError(
RuntimeError: KeyNotFoundException: The given key was not present in the dictionary.. trace:   at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x0001e] in <695d1cc93cca45069c528c15c9fdd749>:0
  at Thor.Procedural.AssetMap`1[T].getAsset (System.String name) [0x00000] in <6afd8f78be764eeba7be30f178fa1cb8>:0
  at Thor.Procedural.ProceduralTools.CreateHouse (Thor.Procedural.Data.ProceduralHouse house, Thor.Procedural.AssetMap`1[T] materialDb, System.Nullable`1[T] position) [0x0035a] in <6afd8f78be764eeba7be30f178fa1cb8>:0
  at UnityStandardAssets.Characters.FirstPerson.BaseFPSAgentController.CreateHouse (Thor.Procedural.Data.ProceduralHouse house) [0x000e1] in <6afd8f78be764eeba7be30f178fa1cb8>:0
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <695d1cc93cca45069c528c15c9fdd749>:0
`

**Comment by mattdeitke** [comment]
Hi @mariiak2021,

this usually means the house JSON is not formatted correctly. Here, it seems like an object’s assetId doesn’t exist in our asset database.

Just to clarify, are you updating/generating new house jsons when you try to generate new scenes, or is this error coming from using house jsons that are provided in this repo (procthor-10k)?

**Comment by mariiak2021** [comment]
Hi @mattdeitke,
Thank you for the answer! I'm loading houses from ProcThor-10k dataset using  prior.load_dataset("procthor-10k"). Then going through all of the 10k houses, finding only those, which have 1 room. Then making in those selected houses rearrangements of the existing objects -> creating .pkl files with starting/target poses and openness in the Ai2Thor rearrangement challenge format.

Can the issue with assetId be related to using the wrong version of Ai2Thor? Can you suggest something to fix it?
Thank you!

**Comment by mattdeitke** [comment]
Do you mind sharing the code you're using to rearrange the objects in the selected houses? Something might be going on there.

Also, upon initializing a Controller, can you pass in `branch="nanna"` - e.g.,
```python
from ai2thor.controller import Controller
controller = Controller(branch="nanna")
```
That may help, too.

**Comment by mariiak2021** [comment]
Hi @mattdeitke,

Using nanna branch didn't help unfortunately. :(

I'm using the code from this GIT repo from Jordi: 
https://github.com/jordis-ai2/ai2thor-rearrangement-procthor/tree/procthor-2022

This branch is already adapted to be used with houses as I see. 
The only files I change are:

1) /utils/procthor_utils.py to load Proc-Thor-10K dataset instead of the not released allenai/houses DS:

```
import pickle
import compress_pickle
import datasets
import prior

class Houses:
    def __init__(
        self, revision="ithor-splits", valid_houses_file=None,
    ):
        if valid_houses_file is None:
            self._data = prior.load_dataset(
                "procthor-10k"
            )
            self._mode = "train"
        else:
            self._data = {"validation": compress_pickle.load(valid_houses_file)}
            self._mode = "validation"

    def mode(self, mode: str):
        if mode in ["val", "valid"]:
            mode = "validation"
        elif mode in ["train"]:
            mode = "train"
        self._mode = mode

    @property
    def current_mode(self):
        return self._mode

    def data(self, pos: int):
        return self[pos]

    def __getitem__(self, pos: int):
        return self._data[self._mode][pos]

    def __len__(self):
        return len(self._data[self._mode])

```
2) /rearrange/procthor_rearrange/environment.py - added additional platform parameter inside create_controller function (line 392) as I'm running code on remote server without GUI:

```
from ai2thor.platform import CloudRendering
self._controller_kwargs["platform"] = CloudRendering

```

**Comment by mattdeitke** [comment]
The code appears correct to me, but I might be missing where this error came from.

Do you have a specific house.json / index into the procthor-10k dataset that raised the error?

Also, I might be missing the code to perform:
> Then making in those selected houses rearrangements of the existing objects -> creating .pkl files with starting/target poses and openness in the Ai2Thor rearrangement challenge format.

Are you able to share that as well?

**Comment by mariiak2021** [comment]
Hi @mattdeitke,

> Do you have a specific house.json / index into the procthor-10k dataset that raised the error?

For example, houses with indexes 14, 97, 91 from procthor-10K dataset always throw this error.

> Then making in those selected houses rearrangements of the existing objects -> creating .pkl files with starting/target poses and openness in the Ai2Thor rearrangement challenge format.

For this purpose (to generate rearrangement scenarios) I'm using this script:
https://github.com/jordis-ai2/ai2thor-rearrangement-procthor/blob/procthor-2022/datagen/procthor_datagen/datagen_runner.py

**Comment by mattdeitke** [comment]
Scenes 14, 96, and 91 are working for me when I test it on Colab. Can you confirm that you're doing something similar to me for creating and changing the scenes?: https://colab.research.google.com/drive/1YA4alLgp9iDOxDfALmRh66LEq3Wb3EoU?usp=sharing

**Comment by mariiak2021** [comment]
@mattdeitke actually in the script I was using instead reset with house dictionary
`controller.reset(scene=house)`
was empty reset with the following CreateHouse action
`self.controller.reset()
self.controller.step(action="CreateHouse", house=house, raise_for_failure=True)`

I tried now to change the code but the result is still the same for house 14 for example. The same error code.

**Comment by mariiak2021** [comment]
@mattdeitke I have some updates.

1) Seems that controller.reset(scene=house) is actually helping! I made some more attempts and the previous error disappear. 
Thank you for that!
I'm using 391b3fae4d4cc026f1522e5acf60953560235971 commit_ID and both with branch="nanna" and without specifying the branch it's working same. I'm testing now this set up for more houses and will let you know if it will go all well!

2) Another question - how can I get correct instance_detection2D using reset with houses instead of scenes?
```
house = houses["train"][96]
controller.reset(scene=house)
event = controller.step(action="RotateRight", renderInstanceSegmentation=True)
a = controller.last_event.instance_detections2D
for k in a.keys():
  print (k)
```
returns only high level objects without children:
```
Fridge|2|1
CounterTop|2|0
wall|2|0.00|8.16|4.08|8.16
wall|2|0.00|0.00|0.00|8.16
room|2
```
For my work is critical to extract this type of information...can you suggest something please? 
Perhaps, it's possible to pass house in a different way to the controller for reset? Or change the definition of instance_detection2D manually?

**Comment by mattdeitke** [comment]
1. Ooh, great!
2. renderInstanceSegmentation=True must be passed to the reset method, instead of the step method. Can you try:

```python
house = houses["train"][96]
controller.reset(scene=house, renderInstanceSegmentation=True)
event = controller.step(action="RotateRight")
a = controller.last_event.instance_detections2D
for k in a.keys():
  print (k)
```

**Comment by mariiak2021** [comment]
Hi @mattdeitke,

2. Oh you are right - I put renderInstanceSegmentation=True in the wrong place, but I just did the experiment as you suggested and the result is exactly he same - no children objects are visible in the returned dictionary.

```
Fridge|2|1
CounterTop|2|0
wall|2|0.00|8.16|4.08|8.16
wall|2|0.00|0.00|0.00|8.16
room|2
```

**Comment by mariiak2021** [comment]
Hi @mattdeitke 
The update regarding 

> Seems that controller.reset(scene=house) is actually helping! I made some more attempts and the previous error disappear.
> Thank you for that!
> I'm using 391b3fae4d4cc026f1522e5acf60953560235971 commit_ID and both with branch="nanna" and without specifying the branch it's working same. I'm testing now this set up for more houses and will let you know if it will go all well!

I realized that the error appeared in case if house from ProcThor-10K has 2 (or more) room types, which don't have a wall between each other - like a studio with kitchen and living room. These houses were considered like 1-room houses by code, which is a mistake.

But I still didn't figure out **how to get the correct instance_detections2D dictionary** - do you have any suggestions?
